fix(package): update vscode to the last ver.
* v1.1.37 is the last version of the node package vscode, which has been deprecated
* With v0.9.9, npm install fails to complete. Key error log:
  * Error: Cannot find module '.../node_modules/vscode/bin/install'